"""empty message

Revision ID: 0e276d407116
Revises: 
Create Date: 2020-11-03 05:15:00.847983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e276d407116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('subscription', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Interval(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('nutrition_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
