"""empty message

Revision ID: 1f46fd0370d5
Revises: ba5a93de4d21
Create Date: 2020-12-06 03:07:01.467816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f46fd0370d5'
down_revision = 'ba5a93de4d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('saturated', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('sugars', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('trans', sa.Text(), nullable=True))
    op.drop_column('nutrition', 'sat_fat')
    op.drop_column('nutrition', 'sugar')
    op.drop_column('nutrition', 'trans_fat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('trans_fat', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nutrition', sa.Column('sugar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nutrition', sa.Column('sat_fat', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('nutrition', 'trans')
    op.drop_column('nutrition', 'sugars')
    op.drop_column('nutrition', 'saturated')
    # ### end Alembic commands ###
