"""empty message

Revision ID: 1f6af6d0cad3
Revises: e600fd706555
Create Date: 2020-11-29 01:50:52.610459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6af6d0cad3'
down_revision = 'e600fd706555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('update_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'update_date')
    # ### end Alembic commands ###
