"""empty message

Revision ID: 426d3e1ef11d
Revises: a59d9f4b029d
Create Date: 2020-11-21 23:08:25.489116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426d3e1ef11d'
down_revision = 'a59d9f4b029d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition', 'recipe_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('recipe_name', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
