"""empty message

Revision ID: 4cc1ea620934
Revises: 0e276d407116
Create Date: 2020-11-03 22:41:59.542594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc1ea620934'
down_revision = '0e276d407116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('vendor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vendor_id')
    # ### end Alembic commands ###
