"""empty message

Revision ID: 52ace62d9e2c
Revises: 82a49bad8f59
Create Date: 2020-11-10 23:34:01.887601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ace62d9e2c'
down_revision = '82a49bad8f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restName', sa.Text(), nullable=True),
    sa.Column('vendorType', sa.Text(), nullable=True),
    sa.Column('applsDate', sa.Date(), nullable=True),
    sa.Column('busLocation', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
