"""empty message

Revision ID: 54baa236a7b9
Revises: c0447f4cda5c
Create Date: 2020-11-10 20:33:52.007281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54baa236a7b9'
down_revision = 'c0447f4cda5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('applsDate', sa.Date(), nullable=True))
    op.drop_column('application', 'appDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('appDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('application', 'applsDate')
    # ### end Alembic commands ###
