"""empty message

Revision ID: 6263ea80a86c
Revises: 6cf36da6705f
Create Date: 2020-11-17 23:02:35.186238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6263ea80a86c'
down_revision = '6cf36da6705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
