"""empty message

Revision ID: 6561c4454534
Revises: c7d83b8aa185
Create Date: 2020-11-12 22:42:39.463409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6561c4454534'
down_revision = 'c7d83b8aa185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
