"""empty message

Revision ID: 9276bf7d3e68
Revises: 6cf36da6705f
Create Date: 2020-11-18 08:19:49.909435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9276bf7d3e68'
down_revision = '6cf36da6705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('userReporter_id', sa.Integer(), nullable=True),
    sa.Column('reportedUser_id', sa.Integer(), nullable=True),
    sa.Column('reportText', sa.Text(), nullable=True),
    sa.Column('reportDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
