"""empty message

Revision ID: b86d1670ecbb
Revises: 5ae89273baf7
Create Date: 2020-11-19 18:43:19.898323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86d1670ecbb'
down_revision = '5ae89273baf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('vendor_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vendor_image_url')
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
