"""empty message

Revision ID: ba5a93de4d21
Revises: 14139ba7bd5e
Create Date: 2020-12-03 18:37:15.155940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5a93de4d21'
down_revision = '14139ba7bd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vendor_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vendor_name')
    # ### end Alembic commands ###
