"""empty message

Revision ID: bf38c530b847
Revises: 36771da80a63
Create Date: 2020-11-27 23:02:15.501948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf38c530b847'
down_revision = '36771da80a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('calories', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('carbs', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('chol', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('fat', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('fiber', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('protein', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('sat_fat', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('sodium', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('sugar', sa.Text(), nullable=True))
    op.add_column('nutrition', sa.Column('trans_fat', sa.Text(), nullable=True))
    op.drop_column('nutrition', 'details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('nutrition', 'trans_fat')
    op.drop_column('nutrition', 'sugar')
    op.drop_column('nutrition', 'sodium')
    op.drop_column('nutrition', 'sat_fat')
    op.drop_column('nutrition', 'protein')
    op.drop_column('nutrition', 'fiber')
    op.drop_column('nutrition', 'fat')
    op.drop_column('nutrition', 'chol')
    op.drop_column('nutrition', 'carbs')
    op.drop_column('nutrition', 'calories')
    # ### end Alembic commands ###
