"""empty message

Revision ID: c0447f4cda5c
Revises: 4cc1ea620934
Create Date: 2020-11-08 01:12:20.340080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0447f4cda5c'
down_revision = '4cc1ea620934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restName', sa.Text(), nullable=True),
    sa.Column('vendorType', sa.Text(), nullable=True),
    sa.Column('appDate', sa.Date(), nullable=True),
    sa.Column('busLocation', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
