"""empty message

Revision ID: f6933dc1ffa0
Revises: 3872b4d48fb0
Create Date: 2020-12-03 03:43:19.002176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6933dc1ffa0'
down_revision = '3872b4d48fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram')
    # ### end Alembic commands ###
