"""empty message

Revision ID: fbcf7cdceeff
Revises: 1f46fd0370d5
Create Date: 2020-12-06 03:07:41.613120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcf7cdceeff'
down_revision = '1f46fd0370d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('cholesterol', sa.Text(), nullable=True))
    op.drop_column('nutrition', 'chol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('chol', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('nutrition', 'cholesterol')
    # ### end Alembic commands ###
